apiVersion: v1
kind: Service
metadata:
    name: "{{ service-name }}"
    labels:
      app: "{{ app }}"
      version: clus-istio
spec:
  ports:
  - name: http
    port: 50001
    protocol: TCP
    targetPort: 50001
  - name: grpc
    port: 51001
    protocol: TCP
    targetPort: 51001
  - name: grpc-tls
    port: 52001
    protocol: TCP
    targetPort: 52001
  clusterIP:  None
  selector:
    app: "{{ app }}"
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: "{{ service-name }}"
spec:
  replicas: {{ replicas }}
  template:
    metadata:
      labels:
        app: "{{ app }}"
        version: clus-istio
    spec:
      containers:
      - name: locpick-prod
        image: beatrak/locpick
        imagePullPolicy: IfNotPresent
        env:
          - name: "LOG_LEVEL"
            value: "{{ log-level }}"
          - name: "SERVICE_NAME"
            value: "{{ service-name }}"
