apiVersion: v1
kind: Service
metadata:
  name: "{{ service-name }}"
  labels:
    app: "{{ app }}"
spec:
  type: NodePort
  ports:
  - port: 50001
    name: http
  selector:
    app: "{{ app }}"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{ service-name }}"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: "{{ app }}"
        version: v-devshell
    spec:
      containers:
      - name: "{{ service-name }}"
        image: beatrak/locpick-devshell
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent #Always
        env:
          - name: "LOG_LEVEL"
            value: "{{ log-level }}"
          - name: "SERVICE_NAME"
            value: "{{ service-name }}"
        volumeMounts:
          - mountPath: /root/app
            name: app-volume
          - mountPath: /root/common
            name: common-volume
        ports:
        - containerPort: 50001
      volumes:
        - name: app-volume
          hostPath:
            path: {{ app-volume-path }}
        - name: common-volume
          hostPath:
      nodeSelector:
        kubernetes.io/hostname: {{ hostname }}

