apiVersion: v1
kind: Pod
metadata:
  name: "locpick-devshell"
  labels:
    app: "locpick-devshell"
    env: dev
spec:
  containers:
  - name: locpick-devshell
    image: beatrak/locpick-devshell
    imagePullPolicy: IfNotPresent
    env:
      - name: "LOG_LEVEL"
        value: "error"
      - name: "SERVICE_NAME"
        value: "locpick-devshell"
    volumeMounts:
      - mountPath: /root/app
        name: app-volume
      - mountPath: /root/common
        name: common-volume
  - name: locpick-envoy-devshell
    image: beatrak/locpick-envoy
    imagePullPolicy: IfNotPresent
    name: envoy
    ports:
      - containerPort: 50001
        name: locpick-api
        protocol: TCP
      - containerPort: 50011
        name: envoy-admin
        protocol: TCP
  volumes:
    - name: app-volume
      hostPath:
        path: /home/cdmitri/src/github.com/cdmitri/beatrak/locpick/locpick-msvc/app
    - name: common-volume
      hostPath:
        path: /home/cdmitri/src/github.com/cdmitri/beatrak/common
  nodeSelector:
    kubernetes.io/hostname: beatrak-ubuntu16




