apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: beacon-to-service
spec:
  destination:
    name: service
  match:
   source:
     name: beacon
  route:
  - labels:
      cluster: on-prem-service-1
    weight: 50
  - labels:
      cluster: on-prem-service-2
    weight: 50
  - labels:
      cluster: cloud-service-1
    weight: 0
