apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: stage1-rr
spec:
  destination:
    name: stage1-dep-istio
  match:
   source:
     name: printhello
     labels:
       version: v1
  route:
  - labels:
      version: v1
      cluster: prem-1
      zone: zp
    weight: 0
  - labels:
      version: shutoff
      cluster: prem-1
      zone: zp
    weight: 100
