apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: stage1-dep-rr-all-shutoff
spec:
  ## Used by services inside the Kubernetes cluster
  destination:
    name: stage1-dep-istio
  precedence: 1
  route:
  - labels:
      app: "stage1-dep-istio"
      cluster: "prem-1"
      zone: "zp"
      version: "v2"
