apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: stage1-rr-all-to-stage1-prem-1
spec:
  destination:
    name: stage1-dep-istio
  precedence: 1
  route:
  - labels:
      app: stage1-dep-istio
      version: v2
