apiVersion: v1
kind: Service
metadata:
    name: {{ service-name }}
    labels:
      app: {{ app }}
spec:
  ports:
  - name: stage1-api
    port: 50001
    protocol: TCP
    targetPort: 50001
  - name: envoy-admin
    port: 50011
    protocol: TCP
    targetPort: 50011
  type: ClusterIP
  clusterIP:  None
  selector:
    app: {{ app }}

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ service-name }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: "{{ app }}"
        version: v-devshell
    spec:
      containers:
      - name: "{{ service-name }}"
        image: beatrak/beacon-devshell
        imagePullPolicy: IfNotPresent
        env:
          - name: "LOG_LEVEL"
            value: "{{ log-level }}"
          - name: "SERVICE_NAME"
            value: "{{ service-name }}"
          - name: "ZONE"
            value: "{{ zone }}"
          - name: "BEACON_SIG_NUMBER"
            value: "{{ beacon-sig-number }}"
          - name: "BEACON_SIG_PS"
            value: "{{ beacon-sig-ps }}"
        volumeMounts:
          - mountPath: /root/beatrak
            name: beatrak-volume
        ports:
        - containerPort: 50001
      volumes:
        - name: beatrak-volume
          hostPath:
            path: "{{ beatrak-volume-path }}"
      nodeSelector:
        kubernetes.io/hostname: "{{ hostname }}"
