apiVersion: v1
kind: Service
metadata:
    name: "{{ service-name }}"
    labels:
      app: "{{ app }}"
spec:
  ports:
  - name: stage1-api
    port: 50006
    protocol: TCP
    targetPort: 50006
  - name: grpc
    port: 51006
    protocol: TCP
    targetPort: 51006
  - name: grpc-tls
    port: 52006
    protocol: TCP
    targetPort: 52006
  clusterIP:  None
  selector:
    app: "{{ app }}"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{ service-name }}"
spec:
  replicas: {{ replicas }}
  template:
    metadata:
      labels:
        app: "{{ app }}"
        cluster: "{{ cluster }}"
        zone: "{{ zone }}"
        version: "{{ version }}"
    spec:
      containers:
      - name: stage1
        image: beatrak/stage1
        imagePullPolicy: IfNotPresent
        env:
          - name: "LOG_LEVEL"
            value: "{{ log-level }}"
          - name: "SERVICE_NAME"
            value: "{{ service-name }}"
          - name: "CLUSTER"
            value: "{{ cluster }}"
          - name: "ZONE"
            value: "{{ zone }}"
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ service-name }}"
  annotations:
    kubernetes.io/ingress.class: "istio"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: "{{ service-name }}"
          servicePort: 50006
---

            
