FROM beatrak/node-base

RUN mkdir -p /root/beatrak
WORKDIR /root/beatrak

COPY ./waitloop.sh ./start-dev.sh /
RUN chmod a+x /waitloop.sh && chmod a+x /start-dev.sh

EXPOSE 8080
CMD ["/waitloop.sh"]



