FROM beatrak/node-base

RUN mkdir -p /root/beatrak
WORKDIR /root/beatrak/locpick/locpick-msvc/app

#RUN mkdir -p /root/app
#RUN mkdir -p /root/common
#RUN mkdir -p /root/beatrak
#ADD ./app /root/app
#ADD ./common /root/common
#WORKDIR /root/common
#RUN npm install
#WORKDIR /root/beatrak/locpick/locpick-msvc/app
#RUN npm install

EXPOSE 8080

CMD ["npm", "start"]



