apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: beacon-rr-to-prem-1
spec:
  destination:
    name: stage1-dep-istio
  precedence: 3
  route:
  - labels:
      app: stage1-dep-istio
      version: v1
      cluster: prem-1
      zone: zp
