apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: beacon-rr-to-prem-1.yaml
spec:
  destination:
    name: stage1-dep-istio
  precedence: 1
  route:
  - labels:
      version: ver1
