apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: beacon-rr-to-prem-2
spec:
  destination:
    name: stage1-dep-istio
  precedence: 1
  route:
  - labels:
      app: stage1-dep-istio
      version: v1
      cluster: prem-2
      zone: zp
